#!/bin/bash
#
# Airbyte + dbt POC Setup Script
# ================================
# One-click setup for the complete ELT pipeline
#
# Usage:
#   ./scripts/setup.sh              # Full setup WITH Airbyte (default)
#   ./scripts/setup.sh --no-airbyte # Setup without Airbyte
#   ./scripts/setup.sh --seed       # Setup with test data (no Airbyte)
#   ./scripts/setup.sh --clean      # Teardown everything
#

set -e  # Exit on first error

# =============================================================================
# CONFIGURATION (defaults, can be overridden by .env)
# =============================================================================
POSTGRES_CONTAINER="n8n-postgres"
POSTGRES_USER="n8n_user"
POSTGRES_PORT="5432"
DOCKER_NETWORK="n8n-network"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# =============================================================================
# GENERATED VARIABLES (written to .env.generated)
# =============================================================================
GEN_DBT_USER="dbt_user"
GEN_DBT_PASSWORD="dbt_password"
GEN_DBT_DB_NAME="dbt_analytics"
GEN_AIRBYTE_DB_USER="airbyte_user"
GEN_AIRBYTE_DB_PASSWORD="airbyte_password"
GEN_AIRBYTE_DB_NAME="airbyte_raw"
GEN_AIRBYTE_WEB_USER="airbyte"
GEN_AIRBYTE_WEB_PASSWORD="password"
GEN_AIRFLOW_ADMIN_USER="admin"
GEN_AIRFLOW_ADMIN_PASSWORD="admin"

# Service URLs
AIRFLOW_URL="http://localhost:8080"
AIRFLOW_HEALTH_URL="http://localhost:8080/health"
AIRBYTE_URL="http://localhost:8000"
AIRBYTE_API_URL="http://localhost:8000/api/v1/health"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
    echo -e "\n${YELLOW}▶ $1${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ ERROR: $1${NC}"
}

print_info() {
    echo -e "  $1"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

abort() {
    echo ""
    print_error "$1"
    echo ""
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${RED}  SETUP ABORTED${NC}"
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "Troubleshooting tips:"
    echo "  1. Check if Docker is running: docker info"
    echo "  2. Check if $POSTGRES_CONTAINER is running: docker ps | grep $POSTGRES_CONTAINER"
    echo "  3. Check container logs: docker logs $POSTGRES_CONTAINER"
    echo "  4. Verify network exists: docker network ls | grep $DOCKER_NETWORK"
    echo ""
    exit 1
}

# =============================================================================
# ENVIRONMENT LOADING
# =============================================================================

load_user_env() {
    print_step "Loading user environment from .env..."
    
    if [[ ! -f "$PROJECT_DIR/.env" ]]; then
        abort "Missing .env file.

To fix, copy from .env.example and adjust values:
  cp .env.example .env
  nano .env"
    fi
    
    # Source .env and export all variables
    set -a
    source "$PROJECT_DIR/.env"
    set +a
    
    # Apply defaults for any missing values
    POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-n8n-postgres}"
    POSTGRES_USER="${POSTGRES_USER:-n8n_user}"
    POSTGRES_PORT="${POSTGRES_PORT:-5432}"
    DOCKER_NETWORK="${DOCKER_NETWORK:-n8n-network}"
    
    print_success "Environment loaded from .env"
    print_info "  POSTGRES_CONTAINER=$POSTGRES_CONTAINER"
    print_info "  POSTGRES_USER=$POSTGRES_USER"
    print_info "  DOCKER_NETWORK=$DOCKER_NETWORK"
}

generate_env_file() {
    print_step "Generating .env.generated..."
    
    cat > "$PROJECT_DIR/.env.generated" << EOF
# ===========================================
# AUTO-GENERATED by setup.sh - DO NOT EDIT
# Regenerated on each setup run
# Generated: $(date -Iseconds)
# ===========================================

# dbt credentials
DBT_USER=${GEN_DBT_USER}
DBT_PASSWORD=${GEN_DBT_PASSWORD}
DBT_DB_NAME=${GEN_DBT_DB_NAME}

# Airbyte DB credentials
AIRBYTE_DB_USER=${GEN_AIRBYTE_DB_USER}
AIRBYTE_DB_PASSWORD=${GEN_AIRBYTE_DB_PASSWORD}
AIRBYTE_DB_NAME=${GEN_AIRBYTE_DB_NAME}

# Airbyte WebUI
AIRBYTE_WEB_USER=${GEN_AIRBYTE_WEB_USER}
AIRBYTE_WEB_PASSWORD=${GEN_AIRBYTE_WEB_PASSWORD}

# Airflow
AIRFLOW_ADMIN_USER=${GEN_AIRFLOW_ADMIN_USER}
AIRFLOW_ADMIN_PASSWORD=${GEN_AIRFLOW_ADMIN_PASSWORD}

# PostgreSQL (inherited from .env)
POSTGRES_HOST_DOCKER=${POSTGRES_CONTAINER}
POSTGRES_HOST_EXTERNAL=localhost
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_CONTAINER=${POSTGRES_CONTAINER}
POSTGRES_USER=${POSTGRES_USER}
DOCKER_NETWORK=${DOCKER_NETWORK}
EOF
    
    print_success ".env.generated created"
}

# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================

check_docker() {
    print_step "Checking Docker availability..."
    
    if ! command -v docker &> /dev/null; then
        abort "Docker is not installed or not in PATH"
    fi
    
    if ! docker info &> /dev/null; then
        abort "Docker daemon is not running. Please start Docker."
    fi
    
    print_success "Docker is available and running"
}

check_postgres_container() {
    print_step "Checking PostgreSQL container ($POSTGRES_CONTAINER)..."
    
    if ! docker ps --format '{{.Names}}' | grep -q "^${POSTGRES_CONTAINER}$"; then
        abort "Container '$POSTGRES_CONTAINER' is not running.
       
       Expected: A running PostgreSQL container named '$POSTGRES_CONTAINER'
       
       To fix:
         - Start your existing n8n stack, OR
         - Create the container manually:
           docker run -d --name $POSTGRES_CONTAINER \\
             -e POSTGRES_PASSWORD=password \\
             -p 5432:5432 \\
             --network $DOCKER_NETWORK \\
             postgres:16-alpine"
    fi
    
    # Check if postgres is accepting connections
    if ! docker exec "$POSTGRES_CONTAINER" pg_isready -U "$POSTGRES_USER" &> /dev/null; then
        abort "PostgreSQL in '$POSTGRES_CONTAINER' is not ready to accept connections.
       
       The container is running but PostgreSQL is not responding.
       Wait a few seconds and try again, or check logs:
         docker logs $POSTGRES_CONTAINER"
    fi
    
    print_success "PostgreSQL container is running and healthy"
}

check_docker_network() {
    print_step "Checking Docker network ($DOCKER_NETWORK)..."
    
    if ! docker network ls --format '{{.Name}}' | grep -q "^${DOCKER_NETWORK}$"; then
        abort "Docker network '$DOCKER_NETWORK' does not exist.
       
       To fix:
         docker network create $DOCKER_NETWORK"
    fi
    
    print_success "Docker network exists"
}

check_database_exists() {
    local db_name="$1"
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -lqt | cut -d \| -f 1 | grep -qw "$db_name"
}

check_user_exists() {
    local user_name="$1"
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$user_name'" | grep -q 1
}

check_schema_exists() {
    local db_name="$1"
    local schema_name="$2"
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d "$db_name" -tAc "SELECT 1 FROM information_schema.schemata WHERE schema_name='$schema_name'" | grep -q 1
}

check_url_responding() {
    local url="$1"
    local timeout="${2:-5}"
    local auth="${3:-}"
    if [[ -n "$auth" ]]; then
        curl --silent --fail --max-time "$timeout" -u "$auth" "$url" > /dev/null 2>&1
    else
        curl --silent --fail --max-time "$timeout" "$url" > /dev/null 2>&1
    fi
}

check_url_with_retry() {
    local url="$1"
    local service_name="$2"
    local max_attempts="${3:-30}"
    local auth="${4:-}"
    local attempt=1
    
    while [[ $attempt -le $max_attempts ]]; do
        if check_url_responding "$url" 5 "$auth"; then
            return 0
        fi
        printf "  Waiting for %s... (%d/%d)\r" "$service_name" "$attempt" "$max_attempts"
        sleep 2
        ((attempt++))
    done
    
    return 1
}

# =============================================================================
# SETUP FUNCTIONS
# =============================================================================

create_databases() {
    print_step "Creating POC databases and users..."
    
    # Check if databases already exist
    if check_database_exists "${GEN_AIRBYTE_DB_NAME}" && check_database_exists "${GEN_DBT_DB_NAME}"; then
        print_info "Databases already exist, skipping creation"
        print_success "Databases verified"
        return 0
    fi
    
    # Create users inline (instead of SQL file for parameterization)
    print_info "Creating users (${GEN_DBT_USER}, ${GEN_AIRBYTE_DB_USER})..."
    
    # Create dbt_user if not exists
    if ! check_user_exists "${GEN_DBT_USER}"; then
        if ! docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -c \
            "CREATE USER ${GEN_DBT_USER} WITH PASSWORD '${GEN_DBT_PASSWORD}';" 2>&1; then
            abort "Failed to create user ${GEN_DBT_USER}"
        fi
        print_info "  Created user: ${GEN_DBT_USER}"
    else
        print_info "  User ${GEN_DBT_USER} already exists"
    fi
    
    # Create airbyte_user if not exists
    if ! check_user_exists "${GEN_AIRBYTE_DB_USER}"; then
        if ! docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -c \
            "CREATE USER ${GEN_AIRBYTE_DB_USER} WITH PASSWORD '${GEN_AIRBYTE_DB_PASSWORD}';" 2>&1; then
            abort "Failed to create user ${GEN_AIRBYTE_DB_USER}"
        fi
        print_info "  Created user: ${GEN_AIRBYTE_DB_USER}"
    else
        print_info "  User ${GEN_AIRBYTE_DB_USER} already exists"
    fi
    
    # Create databases via shell (CREATE DATABASE cannot run inside transaction)
    if ! check_database_exists "${GEN_AIRBYTE_DB_NAME}"; then
        print_info "Creating database: ${GEN_AIRBYTE_DB_NAME}..."
        if ! docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -c \
            "CREATE DATABASE ${GEN_AIRBYTE_DB_NAME} OWNER ${GEN_AIRBYTE_DB_USER};" 2>&1; then
            abort "Failed to create ${GEN_AIRBYTE_DB_NAME} database"
        fi
    fi
    
    if ! check_database_exists "${GEN_DBT_DB_NAME}"; then
        print_info "Creating database: ${GEN_DBT_DB_NAME}..."
        if ! docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -c \
            "CREATE DATABASE ${GEN_DBT_DB_NAME} OWNER ${GEN_DBT_USER};" 2>&1; then
            abort "Failed to create ${GEN_DBT_DB_NAME} database"
        fi
    fi
    
    # Grant cross-database access
    print_info "Granting cross-database access..."
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d postgres -c \
        "GRANT CONNECT ON DATABASE ${GEN_AIRBYTE_DB_NAME} TO ${GEN_DBT_USER};" 2>&1 || true
    
    # Validate databases were created
    if ! check_database_exists "${GEN_AIRBYTE_DB_NAME}"; then
        abort "Database '${GEN_AIRBYTE_DB_NAME}' was not created"
    fi
    
    if ! check_database_exists "${GEN_DBT_DB_NAME}"; then
        abort "Database '${GEN_DBT_DB_NAME}' was not created"
    fi
    
    # Validate users were created
    if ! check_user_exists "${GEN_AIRBYTE_DB_USER}"; then
        abort "User '${GEN_AIRBYTE_DB_USER}' was not created"
    fi
    
    if ! check_user_exists "${GEN_DBT_USER}"; then
        abort "User '${GEN_DBT_USER}' was not created"
    fi
    
    print_success "Databases and users created successfully"
}

create_schemas() {
    print_step "Creating dbt schemas (staging, marts, gold)..."
    
    # Check if schemas already exist
    if check_schema_exists "${GEN_DBT_DB_NAME}" "staging" && \
       check_schema_exists "${GEN_DBT_DB_NAME}" "marts" && \
       check_schema_exists "${GEN_DBT_DB_NAME}" "gold"; then
        print_info "Schemas already exist, skipping creation"
        print_success "Schemas verified"
        return 0
    fi
    
    # Create schemas inline (parameterized)
    print_info "Creating schemas in ${GEN_DBT_DB_NAME}..."
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d "${GEN_DBT_DB_NAME}" -c "
        CREATE SCHEMA IF NOT EXISTS staging;
        CREATE SCHEMA IF NOT EXISTS marts;
        CREATE SCHEMA IF NOT EXISTS gold;
        
        GRANT ALL PRIVILEGES ON SCHEMA staging TO ${GEN_DBT_USER};
        GRANT ALL PRIVILEGES ON SCHEMA marts TO ${GEN_DBT_USER};
        GRANT ALL PRIVILEGES ON SCHEMA gold TO ${GEN_DBT_USER};
        GRANT ALL PRIVILEGES ON SCHEMA public TO ${GEN_DBT_USER};
        
        ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT ALL ON TABLES TO ${GEN_DBT_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA marts GRANT ALL ON TABLES TO ${GEN_DBT_USER};
        ALTER DEFAULT PRIVILEGES IN SCHEMA gold GRANT ALL ON TABLES TO ${GEN_DBT_USER};
    " 2>&1 || abort "Failed to create schemas in ${GEN_DBT_DB_NAME}"
    
    # Validate schemas
    for schema in staging marts gold; do
        if ! check_schema_exists "${GEN_DBT_DB_NAME}" "$schema"; then
            abort "Schema '$schema' was not created in ${GEN_DBT_DB_NAME}"
        fi
    done
    
    print_success "Schemas created successfully"
}

set_permissions() {
    print_step "Setting permissions on ${GEN_AIRBYTE_DB_NAME} database..."
    
    print_info "Granting ${GEN_DBT_USER} read access to ${GEN_AIRBYTE_DB_NAME}..."
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d "${GEN_AIRBYTE_DB_NAME}" -c "
        GRANT USAGE ON SCHEMA public TO ${GEN_DBT_USER};
        GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${GEN_DBT_USER};
        ALTER DEFAULT PRIVILEGES FOR USER ${GEN_AIRBYTE_DB_USER} IN SCHEMA public
            GRANT SELECT ON TABLES TO ${GEN_DBT_USER};
    " 2>&1 || abort "Failed to set permissions on ${GEN_AIRBYTE_DB_NAME}"
    
    print_success "Permissions configured"
}

start_containers() {
    print_step "Starting Docker containers (dbt + Airflow)..."
    
    cd "$PROJECT_DIR"
    
    # Validate docker-compose.yaml exists
    if [[ ! -f "docker-compose.yaml" ]]; then
        abort "docker-compose.yaml not found in $PROJECT_DIR"
    fi
    
    # Start containers
    print_info "Running docker compose up -d..."
    if ! docker compose up -d 2>&1; then
        abort "Failed to start containers.
       
       Check docker-compose.yaml syntax:
         docker compose config
       
       Check for port conflicts:
         - Airflow uses port 8080
         - Ensure no other service is using this port"
    fi
    
    print_success "Containers started"
}

start_airbyte() {
    print_step "Starting Airbyte containers..."
    
    cd "$PROJECT_DIR"
    
    # Validate docker-compose.airbyte.yaml exists
    if [[ ! -f "docker-compose.airbyte.yaml" ]]; then
        abort "docker-compose.airbyte.yaml not found in $PROJECT_DIR"
    fi
    
    # Start Airbyte containers
    print_info "Running docker compose -f docker-compose.airbyte.yaml up -d..."
    print_info "This may take 2-5 minutes on first run (downloading images)..."
    if ! docker compose -f docker-compose.airbyte.yaml up -d 2>&1; then
        abort "Failed to start Airbyte containers.
       
       Check docker-compose.airbyte.yaml syntax:
         docker compose -f docker-compose.airbyte.yaml config
       
       Check for port conflicts:
         - Airbyte uses port 8000
         - Ensure no other service is using this port"
    fi
    
    print_success "Airbyte containers started"
}

wait_for_airbyte() {
    print_step "Waiting for Airbyte to be ready..."
    
    print_info "This may take 2-4 minutes on first run..."
    
    # Wait for Airbyte API to respond (with basic auth)
    # 120 attempts * 2 seconds = 4 minutes max
    if check_url_with_retry "$AIRBYTE_URL" "Airbyte" 120 "airbyte:password"; then
        echo ""
        print_success "Airbyte is responding"
        return 0
    fi
    
    echo ""
    print_warning "Airbyte not responding yet"
    print_info "Check status with: docker logs airbyte-server"
    return 1
}

configure_airbyte() {
    print_step "Configuring Airbyte (Source, Destination, Connection)..."
    
    print_info "Running auto-configuration script..."
    print_info "This includes schema discovery which may take 30-60 seconds..."
    
    # Retry configuration up to 5 times with 10s delay
    # (Airbyte backend may need extra time after webapp responds)
    local max_attempts=5
    local attempt=1
    local connection_id
    
    while [[ $attempt -le $max_attempts ]]; do
        # Run configure script: stderr shows logs, stdout returns connection_id only
        if connection_id=$(python3 "$SCRIPT_DIR/configure_airbyte.py"); then
            print_success "Airbyte configured successfully"
            print_info "Connection ID: $connection_id"
            
            # Set the connection ID as an Airflow variable
            print_info "Setting Airflow variable 'airbyte_connection_id'..."
            if docker exec airflow airflow variables set airbyte_connection_id "$connection_id" &>/dev/null; then
                print_success "Airflow variable set successfully"
            else
                print_warning "Could not set Airflow variable automatically"
                print_info "Set it manually in Airflow UI: Admin → Variables"
                print_info "  Key: airbyte_connection_id"
                print_info "  Value: $connection_id"
            fi
            
            export AIRBYTE_CONNECTION_ID="$connection_id"
            return 0
        fi
        
        print_info "Airbyte backend not ready yet, retrying in 10s... ($attempt/$max_attempts)"
        sleep 10
        ((attempt++))
    done
    
    print_warning "Airbyte auto-configuration failed after $max_attempts attempts"
    print_info "You can configure Airbyte manually via the UI: $AIRBYTE_URL"
    return 1
}

wait_for_airflow() {
    print_step "Waiting for Airflow to be ready..."
    
    local max_attempts=60
    local attempt=1
    
    print_info "This may take 60-90 seconds on first run..."
    
    # First wait for container to be running
    while [[ $attempt -le 15 ]]; do
        if docker exec airflow airflow db check &> /dev/null; then
            break
        fi
        printf "  Initializing Airflow database... (%d/15)\r" "$attempt"
        sleep 2
        ((attempt++))
    done
    echo ""
    
    # Then wait for web server to respond
    print_info "Waiting for Airflow web server..."
    if check_url_with_retry "$AIRFLOW_HEALTH_URL" "Airflow" 45; then
        echo ""
        print_success "Airflow web server is responding"
        return 0
    fi
    
    echo ""
    print_warning "Airflow web server not responding yet"
    print_info "This might be normal on first run. The service may still be starting."
    print_info "Check status with: docker logs airflow"
    return 1
}

verify_airflow_url() {
    print_step "Verifying Airflow UI accessibility..."
    
    if check_url_responding "$AIRFLOW_URL" 5; then
        print_success "Airflow UI is accessible at $AIRFLOW_URL"
        return 0
    else
        print_warning "Airflow UI not accessible yet at $AIRFLOW_URL"
        print_info "The service may still be starting. Try again in a few seconds."
        return 1
    fi
}

wait_for_dbt() {
    print_step "Verifying dbt container..."
    
    local max_attempts=10
    local attempt=1
    
    while [[ $attempt -le $max_attempts ]]; do
        if docker exec dbt-runner dbt --version &> /dev/null; then
            print_success "dbt container is ready"
            return 0
        fi
        
        sleep 1
        ((attempt++))
    done
    
    abort "dbt container is not responding.
       
       Check container status:
         docker ps -a | grep dbt-runner
         docker logs dbt-runner"
}

seed_test_data() {
    print_step "Seeding test data into airbyte_raw..."
    
    print_info "Running seed_test_data.sql..."
    if ! docker exec -i "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d airbyte_raw < "$SCRIPT_DIR/seed_test_data.sql" 2>&1; then
        abort "Failed to seed test data.
       
       Check that airbyte_raw database exists and tables can be created."
    fi
    
    # Validate data was inserted
    local user_count=$(docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -d airbyte_raw -tAc "SELECT COUNT(*) FROM _airbyte_raw_users" 2>/dev/null || echo "0")
    
    if [[ "$user_count" -lt 1 ]]; then
        abort "Test data was not inserted correctly. Expected users in _airbyte_raw_users table."
    fi
    
    print_success "Test data seeded ($user_count users)"
}

# =============================================================================
# SERVICE STATUS CHECK
# =============================================================================

check_all_services() {
    local with_airbyte="${1:-false}"
    
    print_step "Verifying all services are accessible..."
    
    local all_ok=true
    
    # Check Airbyte (if enabled)
    if [[ "$with_airbyte" == "true" ]]; then
        print_info "Checking Airbyte UI..."
        if check_url_responding "$AIRBYTE_URL" 5 "airbyte:password"; then
            AIRBYTE_STATUS="${GREEN}● ONLINE${NC}"
        else
            AIRBYTE_STATUS="${YELLOW}○ STARTING${NC}"
        fi
    else
        AIRBYTE_STATUS="${YELLOW}○ DISABLED${NC}"
    fi
    
    # Check Airflow UI
    print_info "Checking Airflow UI..."
    if check_url_responding "$AIRFLOW_URL" 5; then
        AIRFLOW_STATUS="${GREEN}● ONLINE${NC}"
    else
        AIRFLOW_STATUS="${RED}○ OFFLINE${NC}"
        all_ok=false
    fi
    
    # Check PostgreSQL
    print_info "Checking PostgreSQL..."
    if docker exec "$POSTGRES_CONTAINER" pg_isready -U "$POSTGRES_USER" &> /dev/null; then
        POSTGRES_STATUS="${GREEN}● ONLINE${NC}"
    else
        POSTGRES_STATUS="${RED}○ OFFLINE${NC}"
        all_ok=false
    fi
    
    # Check dbt container
    print_info "Checking dbt container..."
    if docker exec dbt-runner dbt --version &> /dev/null; then
        DBT_STATUS="${GREEN}● READY${NC}"
    else
        DBT_STATUS="${RED}○ NOT READY${NC}"
        all_ok=false
    fi
    
    echo ""
    
    if $all_ok; then
        print_success "All services are online and healthy"
    else
        print_warning "Some services are not fully ready yet"
    fi
    
    return 0
}

print_service_urls() {
    local with_airbyte="${1:-false}"
    
    echo ""
    echo "┌─────────────────────────────────────────────────────────────────────┐"
    echo "│                        SERVICE STATUS                              │"
    echo "├─────────────────────────────────────────────────────────────────────┤"
    printf "│  %-11s %-17s %-26s %-11s│\n" "Service" "Status" "URL" "Credentials"
    echo "├─────────────────────────────────────────────────────────────────────┤"
    # Note: Status strings contain ANSI color codes (11 hidden chars), so we use %-28b for 17 visible chars
    printf "│  %-11s %-28b %-26s %-11s│\n" "Airbyte" "$AIRBYTE_STATUS" "$AIRBYTE_URL" "${GEN_AIRBYTE_WEB_USER}/${GEN_AIRBYTE_WEB_PASSWORD}"
    printf "│  %-11s %-28b %-26s %-11s│\n" "Airflow" "$AIRFLOW_STATUS" "$AIRFLOW_URL" "${GEN_AIRFLOW_ADMIN_USER}/${GEN_AIRFLOW_ADMIN_PASSWORD}"
    printf "│  %-11s %-28b %-26s %-11s│\n" "PostgreSQL" "$POSTGRES_STATUS" "localhost:${POSTGRES_PORT}" "$POSTGRES_USER"
    printf "│  %-11s %-28b %-26s %-11s│\n" "dbt" "$DBT_STATUS" "(CLI only)" "-"
    echo "└─────────────────────────────────────────────────────────────────────┘"
    echo ""
    echo "📌 Quick Links:"
    if [[ "$with_airbyte" == "true" ]]; then
        echo "   • Airbyte UI:     $AIRBYTE_URL"
    fi
    echo "   • Airflow UI:     $AIRFLOW_URL"
    echo "   • Airflow DAGs:   $AIRFLOW_URL/dags/elt_pipeline/grid"
    echo ""
}

# =============================================================================
# CLEANUP FUNCTION
# =============================================================================

cleanup() {
    print_header "CLEANUP: Removing POC resources"
    
    # Load env if available (for variable names), use defaults otherwise
    if [[ -f "$PROJECT_DIR/.env" ]]; then
        set -a
        source "$PROJECT_DIR/.env"
        set +a
    fi
    
    print_step "Stopping containers..."
    cd "$PROJECT_DIR"
    docker compose down 2>/dev/null || true
    docker compose -f docker-compose.airbyte.yaml down -v 2>/dev/null || true
    print_success "Containers stopped"
    
    print_step "Dropping databases..."
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -c "DROP DATABASE IF EXISTS ${GEN_AIRBYTE_DB_NAME};" 2>/dev/null || true
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -c "DROP DATABASE IF EXISTS ${GEN_DBT_DB_NAME};" 2>/dev/null || true
    print_success "Databases dropped"
    
    print_step "Dropping users..."
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -c "DROP USER IF EXISTS ${GEN_DBT_USER};" 2>/dev/null || true
    docker exec "$POSTGRES_CONTAINER" psql -U "$POSTGRES_USER" -c "DROP USER IF EXISTS ${GEN_AIRBYTE_DB_USER};" 2>/dev/null || true
    print_success "Users dropped"
    
    print_step "Removing generated files..."
    rm -f "$PROJECT_DIR/.env.generated" 2>/dev/null || true
    print_success "Generated files removed"
    
    print_header "CLEANUP COMPLETE"
    echo ""
    echo "All POC resources have been removed."
    echo "Your ${POSTGRES_CONTAINER} container and data are intact."
    echo ""
}

# =============================================================================
# MAIN
# =============================================================================

main() {
    local with_airbyte=true
    local with_seed=false
    
    # Parse arguments
    for arg in "$@"; do
        case "$arg" in
            --no-airbyte) with_airbyte=false ;;
            --seed) with_airbyte=false; with_seed=true ;;
        esac
    done
    
    print_header "Airbyte + dbt POC Setup"
    echo ""
    echo "This script will:"
    echo "  1. Verify prerequisites (Docker, PostgreSQL container)"
    echo "  2. Create isolated databases (airbyte_raw, dbt_analytics)"
    echo "  3. Create dbt schemas (staging, marts, gold)"
    echo "  4. Start containers (dbt-runner, Airflow)"
    if [[ "$with_airbyte" == "true" ]]; then
        echo "  5. Start Airbyte (Sample Data connector)"
    elif [[ "$with_seed" == "true" ]]; then
        echo "  5. Seed test data (Faker-like sample data)"
    fi
    echo ""
    
    # Load user environment and generate credentials file
    load_user_env
    generate_env_file
    
    # Prerequisites
    check_docker
    check_docker_network
    check_postgres_container
    
    # Database setup
    create_databases
    create_schemas
    set_permissions
    
    # Container startup
    start_containers
    wait_for_dbt
    wait_for_airflow
    
    # Start Airbyte if requested
    if [[ "$with_airbyte" == "true" ]]; then
        start_airbyte
        wait_for_airbyte
        configure_airbyte
    # Or seed test data if requested
    elif [[ "$with_seed" == "true" ]]; then
        seed_test_data
    fi
    
    # Verify all services and show status
    check_all_services "$with_airbyte"
    
    # Success message
    print_header "SETUP COMPLETE"
    echo ""
    echo -e "${GREEN}Your ELT pipeline is ready!${NC}"
    
    print_service_urls "$with_airbyte"
    
    echo "🚀 Next steps:"
    if [[ "$with_airbyte" == "true" ]]; then
        echo "   1. Open Airbyte UI: $AIRBYTE_URL (airbyte/password)"
        echo "      ✓ Source, Destination, and Connection are pre-configured!"
        echo "   2. Go to Connections tab and trigger the first sync manually"
        echo "   3. Open Airflow UI: $AIRFLOW_URL → Trigger 'elt_pipeline' DAG"
        if [[ -n "${AIRBYTE_CONNECTION_ID:-}" ]]; then
            echo ""
            echo "   📋 Connection ID: $AIRBYTE_CONNECTION_ID"
            echo "      (Already set as Airflow variable)"
        fi
    else
        echo "   1. Open Airflow UI: $AIRFLOW_URL"
        echo "   2. Find 'elt_pipeline' DAG"
        echo "   3. Toggle ON and click 'Trigger DAG'"
    fi
    echo ""
    echo "🖥️  CLI Quick Start:"
    echo "   ./scripts/run_pipeline.sh    # Trigger & monitor pipeline in terminal"
    echo ""
    if [[ "$with_airbyte" != "true" && "$with_seed" != "true" ]]; then
        echo "💡 Tip: Run with --seed to load test data, or without flags for full Airbyte:"
        echo "   ./scripts/setup.sh --seed"
        echo "   ./scripts/setup.sh"
        echo ""
    fi
    echo "🧹 To tear down the POC:"
    echo "   ./scripts/setup.sh --clean"
    echo ""
}

# =============================================================================
# ENTRY POINT
# =============================================================================

case "${1:-}" in
    --clean)
        cleanup
        ;;
    --seed|--no-airbyte|"")
        main "$@"
        ;;
    --help|-h)
        echo "Usage: $0 [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  (none)         Full setup WITH Airbyte (default)"
        echo "  --no-airbyte   Full setup without Airbyte containers"
        echo "  --seed         Full setup + test data (no Airbyte)"
        echo "  --clean        Tear down all POC resources"
        echo "  --help         Show this help message"
        echo ""
        ;;
    *)
        echo "Unknown option: $1"
        echo "Run '$0 --help' for usage"
        exit 1
        ;;
esac
